[2024-08-16T19:05:21.403+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_data_after_retrain.update_data_after_retrain manual__2024-08-16T19:05:16.358190+00:00 [queued]>
[2024-08-16T19:05:21.420+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_data_after_retrain.update_data_after_retrain manual__2024-08-16T19:05:16.358190+00:00 [queued]>
[2024-08-16T19:05:21.421+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-08-16T19:05:21.452+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): update_data_after_retrain> on 2024-08-16 19:05:16.358190+00:00
[2024-08-16T19:05:21.465+0000] {standard_task_runner.py:60} INFO - Started process 2681 to run task
[2024-08-16T19:05:21.474+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'update_data_after_retrain', 'update_data_after_retrain', 'manual__2024-08-16T19:05:16.358190+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/update_data_after_retrain.py', '--cfg-path', '/tmp/tmpiw545rb5']
[2024-08-16T19:05:21.476+0000] {standard_task_runner.py:88} INFO - Job 42: Subtask update_data_after_retrain
[2024-08-16T19:05:21.499+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-16T19:05:21.591+0000] {task_command.py:423} INFO - Running <TaskInstance: update_data_after_retrain.update_data_after_retrain manual__2024-08-16T19:05:16.358190+00:00 [running]> on host f23221e116fc
[2024-08-16T19:05:21.852+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_data_after_retrain' AIRFLOW_CTX_TASK_ID='update_data_after_retrain' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T19:05:16.358190+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-16T19:05:16.358190+00:00'
[2024-08-16T19:05:21.854+0000] {update_data_after_retrain.py:39} INFO - L'entrainenement est terminé : True
[2024-08-16T19:05:21.855+0000] {update_data_after_retrain.py:41} INFO - Garder le modèle réentrainé : True
[2024-08-16T19:05:21.862+0000] {update_data_after_retrain.py:43} INFO - Data deja intégré dans le modèle : True
[2024-08-16T19:05:21.863+0000] {update_data_after_retrain.py:47} INFO - now let push data from temp
[2024-08-16T19:05:21.971+0000] {update_data_after_retrain.py:57} INFO - repo new cleaned
[2024-08-16T19:05:24.998+0000] {update_data_after_retrain.py:70} INFO - X_train, y_train are updated in train repo
[2024-08-16T19:05:25.025+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2024-08-16T19:05:25.030+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-08-16T19:05:27.297+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-16T19:05:27.314+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=update_data_after_retrain, task_id=update_data_after_retrain, execution_date=20240816T190516, start_date=20240816T190521, end_date=20240816T190527
[2024-08-16T19:05:27.371+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-16T19:05:27.430+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
