[2024-08-16T19:02:20.769+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_data_management.pull_new_data manual__2024-08-16T19:02:14.491855+00:00 [queued]>
[2024-08-16T19:02:20.826+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_data_management.pull_new_data manual__2024-08-16T19:02:14.491855+00:00 [queued]>
[2024-08-16T19:02:20.826+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-08-16T19:02:21.001+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): pull_new_data> on 2024-08-16 19:02:14.491855+00:00
[2024-08-16T19:02:21.079+0000] {standard_task_runner.py:60} INFO - Started process 2565 to run task
[2024-08-16T19:02:21.128+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'new_data_management', 'pull_new_data', 'manual__2024-08-16T19:02:14.491855+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/new_data_management.py', '--cfg-path', '/tmp/tmpscbkl1b8']
[2024-08-16T19:02:21.137+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask pull_new_data
[2024-08-16T19:02:21.216+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-16T19:02:21.411+0000] {task_command.py:423} INFO - Running <TaskInstance: new_data_management.pull_new_data manual__2024-08-16T19:02:14.491855+00:00 [running]> on host f23221e116fc
[2024-08-16T19:02:21.731+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='new_data_management' AIRFLOW_CTX_TASK_ID='pull_new_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T19:02:14.491855+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-16T19:02:14.491855+00:00'
[2024-08-16T19:02:21.744+0000] {new_data_management.py:157} INFO - Pull new data from bucket my-karma-bucket
[2024-08-16T19:02:21.763+0000] {new_data_management.py:165} INFO - sample_size : 488
[2024-08-16T19:02:23.210+0000] {new_data_management.py:174} INFO - df_train_new shape : (5088, 5)
[2024-08-16T19:02:23.211+0000] {new_data_management.py:175} INFO - df_stock shape : (37370, 5)
[2024-08-16T19:02:26.961+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-16T19:02:27.036+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=new_data_management, task_id=pull_new_data, execution_date=20240816T190214, start_date=20240816T190220, end_date=20240816T190227
[2024-08-16T19:02:27.299+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-16T19:02:27.381+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
