[2024-08-16T17:24:54.657+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bucket_push_test.pull2bucket manual__2024-08-16T17:24:47.884390+00:00 [queued]>
[2024-08-16T17:24:54.671+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bucket_push_test.pull2bucket manual__2024-08-16T17:24:47.884390+00:00 [queued]>
[2024-08-16T17:24:54.671+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-08-16T17:24:54.695+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): pull2bucket> on 2024-08-16 17:24:47.884390+00:00
[2024-08-16T17:24:54.703+0000] {standard_task_runner.py:60} INFO - Started process 305 to run task
[2024-08-16T17:24:54.711+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'bucket_push_test', 'pull2bucket', 'manual__2024-08-16T17:24:47.884390+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/bucket_push_test.py', '--cfg-path', '/tmp/tmp7qdhgibx']
[2024-08-16T17:24:54.713+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask pull2bucket
[2024-08-16T17:24:54.738+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-16T17:24:54.784+0000] {task_command.py:423} INFO - Running <TaskInstance: bucket_push_test.pull2bucket manual__2024-08-16T17:24:47.884390+00:00 [running]> on host de367639f381
[2024-08-16T17:24:54.948+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bucket_push_test' AIRFLOW_CTX_TASK_ID='pull2bucket' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T17:24:47.884390+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-16T17:24:47.884390+00:00'
[2024-08-16T17:24:55.341+0000] {logging_mixin.py:188} INFO - Credentials AWS non disponibles.
[2024-08-16T17:24:55.341+0000] {bucket_push_test.py:45} INFO - MAYDE MAYDE
[2024-08-16T17:24:55.342+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-16T17:24:55.359+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=bucket_push_test, task_id=pull2bucket, execution_date=20240816T172447, start_date=20240816T172454, end_date=20240816T172455
[2024-08-16T17:24:55.446+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-16T17:24:55.479+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
