[2024-08-16T18:50:08.679+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_data_management.pull_new_data manual__2024-08-16T18:50:03.449366+00:00 [queued]>
[2024-08-16T18:50:08.690+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_data_management.pull_new_data manual__2024-08-16T18:50:03.449366+00:00 [queued]>
[2024-08-16T18:50:08.690+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-08-16T18:50:08.712+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): pull_new_data> on 2024-08-16 18:50:03.449366+00:00
[2024-08-16T18:50:08.718+0000] {standard_task_runner.py:60} INFO - Started process 2144 to run task
[2024-08-16T18:50:08.723+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'new_data_management', 'pull_new_data', 'manual__2024-08-16T18:50:03.449366+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/new_data_management.py', '--cfg-path', '/tmp/tmpu_fjzdeb']
[2024-08-16T18:50:08.725+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask pull_new_data
[2024-08-16T18:50:08.746+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-16T18:50:08.826+0000] {task_command.py:423} INFO - Running <TaskInstance: new_data_management.pull_new_data manual__2024-08-16T18:50:03.449366+00:00 [running]> on host f23221e116fc
[2024-08-16T18:50:08.994+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='new_data_management' AIRFLOW_CTX_TASK_ID='pull_new_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T18:50:03.449366+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-16T18:50:03.449366+00:00'
[2024-08-16T18:50:08.996+0000] {new_data_management.py:153} INFO - Pull new data from bucket my-karma-bucket
[2024-08-16T18:50:08.997+0000] {new_data_management.py:161} INFO - sample_size : 488
[2024-08-16T18:50:09.573+0000] {new_data_management.py:170} INFO - df_train_new shape : (3624, 5)
[2024-08-16T18:50:09.573+0000] {new_data_management.py:171} INFO - df_stock shape : (38834, 5)
[2024-08-16T18:50:10.736+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-16T18:50:10.751+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=new_data_management, task_id=pull_new_data, execution_date=20240816T185003, start_date=20240816T185008, end_date=20240816T185010
[2024-08-16T18:50:10.829+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-16T18:50:10.878+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
