[2024-09-07T14:39:43.357+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_data_management.pull_new_data manual__2024-09-07T14:39:33.987817+00:00 [queued]>
[2024-09-07T14:39:43.415+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_data_management.pull_new_data manual__2024-09-07T14:39:33.987817+00:00 [queued]>
[2024-09-07T14:39:43.434+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-09-07T14:39:43.488+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): pull_new_data> on 2024-09-07 14:39:33.987817+00:00
[2024-09-07T14:39:43.523+0000] {standard_task_runner.py:60} INFO - Started process 3728 to run task
[2024-09-07T14:39:43.553+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'new_data_management', 'pull_new_data', 'manual__2024-09-07T14:39:33.987817+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/new_data_management.py', '--cfg-path', '/tmp/tmp_o2d8oqu']
[2024-09-07T14:39:43.558+0000] {standard_task_runner.py:88} INFO - Job 119: Subtask pull_new_data
[2024-09-07T14:39:43.621+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-09-07T14:39:43.763+0000] {task_command.py:423} INFO - Running <TaskInstance: new_data_management.pull_new_data manual__2024-09-07T14:39:33.987817+00:00 [running]> on host 74653e659746
[2024-09-07T14:39:44.206+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='new_data_management' AIRFLOW_CTX_TASK_ID='pull_new_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T14:39:33.987817+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-07T14:39:33.987817+00:00'
[2024-09-07T14:39:44.219+0000] {new_data_management.py:162} INFO - L'entrainenement est terminé : True
[2024-09-07T14:39:44.225+0000] {new_data_management.py:164} INFO - Garder le modèle réentrainé : True
[2024-09-07T14:39:44.229+0000] {new_data_management.py:166} INFO - Data deja intégré dans le modèle : False
[2024-09-07T14:39:44.231+0000] {new_data_management.py:169} INFO - Pull new data from bucket my-karma-bucket
[2024-09-07T14:39:44.232+0000] {new_data_management.py:177} INFO - sample_size : 198
[2024-09-07T14:39:45.002+0000] {new_data_management.py:186} INFO - df_train_new shape : (594, 5)
[2024-09-07T14:39:45.003+0000] {new_data_management.py:187} INFO - df_stock shape : (32656, 5)
[2024-09-07T14:39:47.516+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-09-07T14:39:47.554+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=new_data_management, task_id=pull_new_data, execution_date=20240907T143933, start_date=20240907T143943, end_date=20240907T143947
[2024-09-07T14:39:47.683+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-09-07T14:39:47.787+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
