[2024-08-16T17:14:09.780+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bucket_push_test.pull2bucket manual__2024-08-16T17:14:02.383254+00:00 [queued]>
[2024-08-16T17:14:09.821+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bucket_push_test.pull2bucket manual__2024-08-16T17:14:02.383254+00:00 [queued]>
[2024-08-16T17:14:09.826+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-08-16T17:14:09.864+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): pull2bucket> on 2024-08-16 17:14:02.383254+00:00
[2024-08-16T17:14:09.880+0000] {standard_task_runner.py:60} INFO - Started process 683 to run task
[2024-08-16T17:14:09.902+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'bucket_push_test', 'pull2bucket', 'manual__2024-08-16T17:14:02.383254+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/bucket_push_test.py', '--cfg-path', '/tmp/tmp9v9u_ptl']
[2024-08-16T17:14:09.904+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask pull2bucket
[2024-08-16T17:14:09.941+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-16T17:14:10.019+0000] {task_command.py:423} INFO - Running <TaskInstance: bucket_push_test.pull2bucket manual__2024-08-16T17:14:02.383254+00:00 [running]> on host 34eae30695aa
[2024-08-16T17:14:10.225+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bucket_push_test' AIRFLOW_CTX_TASK_ID='pull2bucket' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T17:14:02.383254+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-16T17:14:02.383254+00:00'
[2024-08-16T17:14:10.711+0000] {logging_mixin.py:188} INFO - Credentials AWS non disponibles.
[2024-08-16T17:14:10.711+0000] {bucket_push_test.py:45} INFO - MAYDE MAYDE
[2024-08-16T17:14:10.712+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-16T17:14:10.728+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=bucket_push_test, task_id=pull2bucket, execution_date=20240816T171402, start_date=20240816T171409, end_date=20240816T171410
[2024-08-16T17:14:10.814+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-16T17:14:10.856+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
