[2024-09-07T14:36:12.356+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_data_management.pull_new_data manual__2024-09-07T14:36:01.319398+00:00 [queued]>
[2024-09-07T14:36:12.388+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_data_management.pull_new_data manual__2024-09-07T14:36:01.319398+00:00 [queued]>
[2024-09-07T14:36:12.389+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-09-07T14:36:12.442+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): pull_new_data> on 2024-09-07 14:36:01.319398+00:00
[2024-09-07T14:36:12.462+0000] {standard_task_runner.py:60} INFO - Started process 3618 to run task
[2024-09-07T14:36:12.475+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'new_data_management', 'pull_new_data', 'manual__2024-09-07T14:36:01.319398+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/new_data_management.py', '--cfg-path', '/tmp/tmpau9z1qcn']
[2024-09-07T14:36:12.482+0000] {standard_task_runner.py:88} INFO - Job 111: Subtask pull_new_data
[2024-09-07T14:36:12.537+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-09-07T14:36:12.656+0000] {task_command.py:423} INFO - Running <TaskInstance: new_data_management.pull_new_data manual__2024-09-07T14:36:01.319398+00:00 [running]> on host 74653e659746
[2024-09-07T14:36:13.129+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='new_data_management' AIRFLOW_CTX_TASK_ID='pull_new_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T14:36:01.319398+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-07T14:36:01.319398+00:00'
[2024-09-07T14:36:13.136+0000] {new_data_management.py:162} INFO - L'entrainenement est terminé : True
[2024-09-07T14:36:13.136+0000] {new_data_management.py:164} INFO - Garder le modèle réentrainé : True
[2024-09-07T14:36:13.139+0000] {new_data_management.py:166} INFO - Data deja intégré dans le modèle : False
[2024-09-07T14:36:13.139+0000] {new_data_management.py:169} INFO - Pull new data from bucket my-karma-bucket
[2024-09-07T14:36:13.171+0000] {new_data_management.py:177} INFO - sample_size : 198
[2024-09-07T14:36:14.907+0000] {new_data_management.py:186} INFO - df_train_new shape : (198, 5)
[2024-09-07T14:36:14.908+0000] {new_data_management.py:187} INFO - df_stock shape : (33052, 5)
[2024-09-07T14:36:20.698+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-09-07T14:36:20.780+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=new_data_management, task_id=pull_new_data, execution_date=20240907T143601, start_date=20240907T143612, end_date=20240907T143620
[2024-09-07T14:36:20.993+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-09-07T14:36:21.167+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
