[2024-09-07T14:44:06.736+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_data_management.send2bucket manual__2024-09-07T14:43:09.927431+00:00 [queued]>
[2024-09-07T14:44:06.802+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_data_management.send2bucket manual__2024-09-07T14:43:09.927431+00:00 [queued]>
[2024-09-07T14:44:06.803+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-09-07T14:44:06.890+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): send2bucket> on 2024-09-07 14:43:09.927431+00:00
[2024-09-07T14:44:06.960+0000] {standard_task_runner.py:60} INFO - Started process 3895 to run task
[2024-09-07T14:44:06.982+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'new_data_management', 'send2bucket', 'manual__2024-09-07T14:43:09.927431+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/new_data_management.py', '--cfg-path', '/tmp/tmpmklms8xv']
[2024-09-07T14:44:06.985+0000] {standard_task_runner.py:88} INFO - Job 138: Subtask send2bucket
[2024-09-07T14:44:07.086+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-09-07T14:44:07.264+0000] {task_command.py:423} INFO - Running <TaskInstance: new_data_management.send2bucket manual__2024-09-07T14:43:09.927431+00:00 [running]> on host 74653e659746
[2024-09-07T14:44:07.639+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='new_data_management' AIRFLOW_CTX_TASK_ID='send2bucket' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T14:43:09.927431+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-07T14:43:09.927431+00:00'
[2024-09-07T14:44:07.732+0000] {logging_mixin.py:188} INFO - retrain: False
[2024-09-07T14:44:07.733+0000] {new_data_management.py:121} INFO - retrain value from task 4 : False
[2024-09-07T14:44:07.735+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-09-07T14:44:07.786+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=new_data_management, task_id=send2bucket, execution_date=20240907T144309, start_date=20240907T144406, end_date=20240907T144407
[2024-09-07T14:44:07.867+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-09-07T14:44:07.974+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
